<?php



/**
 * Implements hook_menu_alter().
 */
function drupalcl_menu_alter(&$items) {
  $items['node/%/issues']['access callback'] = 'drupalcl_access_node_proyect';
  $items['node/%/issues']['access arguments'] = array(1);
}


/**
 * Access callback.
 */
function drupalcl_access_node_proyect($nid) {
  if (is_numeric($nid) && ($node = node_load($nid))) {
    if ($node->type == 'proyecto') {
      return TRUE;
    }
  }

  return FALSE;
}


/**
 * Implements hook_module_implements_alter().
 */
function drupalcl_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'menu_alter') {
    $module = $implementations['drupalcl'];
    unset($implementations['drupalcl']);
    $implementations['drupalcl'] = $module;
  }
}


/**
 * Implements hook_views_api().
 */
function drupalcl_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'drupalcl') . '/views',
  );
}


function drupalcl_rules_action_send_mails($emails, $subject, $message, $from = NULL, $langcode, $settings, RulesState $state, RulesPlugin $element) {
  $to = array_filter($emails, 'drupalcl_only_valid_email');

  rules_action_mail(implode(',', $to), $subject, $message, $from, $langcode, $settings, $state, $element);
}


function drupalcl_only_valid_email($email) {
  return (is_string($email) && valid_email_address($email));
}



